# SinhalaMMLU Buddhism Subdomain Evaluation — v3

**Four evaluation modes:**
1. `Base` — `meta-llama/Meta-Llama-3.1-8B-Instruct` (no adapters, no RAG)
2. `Base + RAG` — Base model, prompt augmented with Tripiṭaka passages from Qdrant
3. `LoRA` — Base + your LoRA adapters (`RaniduG/llama-3.1-8b-ift-buddhist-qa-v6`)
4. `LoRA + RAG` — LoRA model + same RAG augmentation

**Dataset:** `naist-nlp/SinhalaMMLU` — Buddhism subject  
**Embeddings:** `RaniduG/sinhala-tripitaka-embeddings` loaded into in-memory Qdrant  
**Prompt fix:** Explicit bilingual instruction forcing letter-only output

## Cell 1 — Install Dependencies

In [11]:
import sys, os
os.environ['TOKENIZERS_PARALLELISM'] = 'false'

!{sys.executable} -m pip install -q --upgrade pip

# Purge bitsandbytes to avoid stale mixed installs
!{sys.executable} -m pip uninstall -y bitsandbytes
!rm -rf /venv/main/lib/python3.12/site-packages/bitsandbytes
!rm -rf /venv/main/lib/python3.12/site-packages/bitsandbytes-*.dist-info

# bitsandbytes: pre-built CUDA 12.x wheel
!{sys.executable} -m pip install -q --no-cache-dir \
    'bitsandbytes>=0.46.1' \
    --extra-index-url https://huggingface.github.io/bitsandbytes-wheels/

# Core ML stack — peft 0.18.1 matches adapter_config.json peft_version
!{sys.executable} -m pip install -q --no-cache-dir \
    'peft==0.18.1' \
    'accelerate>=0.33.0' \
    'datasets>=2.21.0' \
    'tqdm' 'pandas' 'scipy'

# RAG stack: Qdrant in-memory + sentence-transformers for query encoding
!{sys.executable} -m pip install -q --no-cache-dir \
    'qdrant-client>=1.9.0' \
    'sentence-transformers>=2.7.0'

print('All packages installed.')

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Found existing installation: bitsandbytes 0.45.5
Uninstalling bitsandbytes-0.45.5:
  Successfully uninstalled bitsandbytes-0.45.5
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
All packages installed.

## Cell 2 — Configuration

In [1]:
import os
os.environ['TOKENIZERS_PARALLELISM'] = 'false'

# ── EDIT THESE ────────────────────────────────────────────────────────────────
HF_TOKEN          = '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'
BASE_MODEL_ID     = 'meta-llama/Meta-Llama-3.1-8B-Instruct'
LORA_ADAPTER_REPO = 'RaniduG/llama-3.1-8b-ift-buddhist-qa-v6'

# Your HF dataset with pre-computed Tripitaka embeddings
EMBEDDINGS_REPO   = 'RaniduG/sinhala-tripitaka-embeddings'

# The sentence-transformer model used to CREATE those embeddings.
# IMPORTANT: this must be the exact model you used when building the index.
# Update this if you used a different encoder (e.g. LaBSE, multilingual-e5-large).
QUERY_ENCODER_ID  = "intfloat/multilingual-e5-large"

DATASET_ID    = 'naist-nlp/SinhalaMMLU'
SUBDOMAIN     = 'buddhism'
DATASET_SPLIT = 'train'

# True  = 4-bit NF4 (~5 GB VRAM)  |  False = bfloat16 (~16 GB VRAM)
USE_QUANTIZATION = True

# int for a quick smoke-test (e.g. 20), None for all 162 Buddhism examples
MAX_SAMPLES  = None

# Number of Tripitaka passages to inject per question in RAG mode
RAG_TOP_K = 3
# ─────────────────────────────────────────────────────────────────────────────

print('Configuration loaded.')
print(f'  Base model       : {BASE_MODEL_ID}')
print(f'  LoRA adapter     : {LORA_ADAPTER_REPO}')
print(f'  Embeddings repo  : {EMBEDDINGS_REPO}')
print(f'  Query encoder    : {QUERY_ENCODER_ID}')
print(f'  Quantization     : {USE_QUANTIZATION}')
print(f'  RAG top-k        : {RAG_TOP_K}')

Configuration loaded.
  Base model       : meta-llama/Meta-Llama-3.1-8B-Instruct
  LoRA adapter     : RaniduG/llama-3.1-8b-ift-buddhist-qa-v6
  Embeddings repo  : RaniduG/sinhala-tripitaka-embeddings
  Query encoder    : intfloat/multilingual-e5-large
  Quantization     : True
  RAG top-k        : 3

## Cell 3 — Imports

In [2]:
import gc
import re
import torch
import numpy as np
import pandas as pd
from tqdm.auto import tqdm
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from peft import PeftModel

DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'Imports complete. Device: {DEVICE}')
if DEVICE == 'cuda':
    print(f'  GPU  : {torch.cuda.get_device_name(0)}')
    print(f'  VRAM : {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB')

Imports complete. Device: cuda
  GPU  : NVIDIA GeForce RTX 4090
  VRAM : 25.3 GB

## Cell 4 — Load and Filter Dataset

In [3]:
print(f'Loading SinhalaMMLU ({DATASET_SPLIT} split) ...')
dataset = load_dataset(DATASET_ID, split=DATASET_SPLIT, token=HF_TOKEN)
print(f'  Total rows : {len(dataset)}')

buddhism_data = dataset.filter(
    lambda ex: SUBDOMAIN.lower() in str(ex['subject']).lower()
)
print(f'  Buddhism rows : {len(buddhism_data)}')

# Remove any rows with out-of-range answer index
buddhism_data = buddhism_data.filter(
    lambda ex: isinstance(ex['answer'], int) and 0 <= ex['answer'] <= 3
)
print(f'  After validity filter : {len(buddhism_data)}')

if MAX_SAMPLES is not None:
    buddhism_data = buddhism_data.select(range(min(MAX_SAMPLES, len(buddhism_data))))
    print(f'  Smoke-test truncated to : {len(buddhism_data)}')

ex0 = buddhism_data[0]
print(f'\nFirst example:')
print(f'  Q  : {ex0["question"]}')
for i, c in enumerate(ex0['choices']):
    marker = ' <-- correct' if i == ex0['answer'] else ''
    print(f'  {["A","B","C","D"][i]}. {c}{marker}')

Loading SinhalaMMLU (train split) ...
  Total rows : 1851
  Buddhism rows : 162
  After validity filter : 132

First example:
  Q  : මනු ලොව උපත ලැබීමට ප්‍රථම අප මහා බෝසතාණෝ උපත ලබා සිටියේ,
  A. තුසිත දෙව් ලොවේය.
  B. බ්‍රහ්ම ලොවේය. <-- correct
  C. නාග භවනේය.
  D. සක්‍ර භවනේය.

## Cell 5 — Prompt Builders

**Root cause of Sinhala generation:** The old prompt said `Answer with only the letter` in English, but the model — especially after Buddhist fine-tuning — pattern-matched the Sinhala question and continued generating in Sinhala. Three changes fix this:
1. **Bilingual system prompt** — repeats the instruction in Sinhala so the fine-tuned model cannot ignore it
2. **Forced completion prefix** `The correct answer is:` — the next token the model needs to produce is just the letter
3. **Stronger regex parser** — handles edge cases like `A.`, `A)`, `The answer is A`

In [4]:
CHOICE_LABELS = ['A', 'B', 'C', 'D']
QUESTION_KEY  = 'question'
CHOICES_KEY   = 'choices'
ANSWER_KEY    = 'answer'

# Bilingual system prompt — critical for LoRA model that was trained on Sinhala
SYSTEM_PROMPT = (
    'You are an expert on Buddhist philosophy and the Tripitaka (\u0dad\u0dca\u200d\u0dbb\u0dd2\u0db4\u0dd2\u0da7\u0d9a\u0dba). '
    'You will be given a multiple-choice question written in Sinhala. '
    'You MUST respond with ONLY a single capital letter: A, B, C, or D. '
    'Do NOT write your answer in Sinhala. Do NOT explain your reasoning. '
    'Output the letter and nothing else. '
    '\u0d94\u0db6 \u0d9a\u0dbd \u0dba\u0dd4\u0dad\u0dca\u0dad\u0dda A, B, C \u0dc4\u0ddd D \u0dba\u0db1 \u0d85\u0d9a\u0dd4\u0dbb\u0dda\u0db1\u0dca \u0db4\u0db8\u0dab\u0d9a\u0dca \u0db4\u0dd2\u0dbd\u0dd2\u0dad\u0dd4\u0dbb\u0dd4 \u0daf\u0dd3\u0db8\u0dba\u0dd2.'
)


def build_prompt(example: dict, tokenizer, context_passages: list = None) -> str:
    """
    Build a Llama-3-Instruct MCQ prompt.
    If context_passages is provided (RAG mode), they are injected before the question.
    """
    question = example[QUESTION_KEY]
    choices  = example[CHOICES_KEY]

    options_text = '\n'.join(
        f'{label}. {choice}'
        for label, choice in zip(CHOICE_LABELS, choices)
    )

    rag_block = ''
    if context_passages:
        formatted = '\n\n'.join(
            f'[Passage {i+1}]: {p}' for i, p in enumerate(context_passages)
        )
        rag_block = (
            f'Relevant passages from the Tripitaka:\n\n{formatted}\n\n---\n\n'
        )

    user_message = (
        f'{rag_block}'
        f'Question: {question}\n\n'
        f'{options_text}\n\n'
        # Forced prefix: model only needs to emit the letter
        f'The correct answer is:'
    )

    messages = [
        {'role': 'system', 'content': SYSTEM_PROMPT},
        {'role': 'user',   'content': user_message},
    ]

    return tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )


def get_ground_truth_label(example: dict) -> str:
    answer = example[ANSWER_KEY]
    if isinstance(answer, int) and 0 <= answer <= 3:
        return CHOICE_LABELS[answer]
    return str(answer).strip().upper()


def extract_predicted_label(generated_text: str) -> str:
    """
    Robust parser — handles: 'A', ' A.', 'A)', 'The answer is A', ' A\n', etc.
    Falls back to 'X' (wrong) if no letter found.
    """
    text = generated_text.strip()
    # Pattern 1: letter right after the forced prefix context
    m = re.match(r'^\s*([ABCD])[^a-z]?', text, re.IGNORECASE)
    if m:
        return m.group(1).upper()
    # Pattern 2: 'answer is A' or 'is: A'
    m = re.search(r'(?:answer is|is:?)\s*([ABCD])\b', text, re.IGNORECASE)
    if m:
        return m.group(1).upper()
    # Pattern 3: first A/B/C/D character anywhere
    for char in text:
        if char.upper() in CHOICE_LABELS:
            return char.upper()
    return 'X'


print('Prompt builders ready.')
s = buddhism_data[0]
print(f'  Sample Q       : {s["question"][:70]}...')
print(f'  Ground truth   : {get_ground_truth_label(s)} -> {s["choices"][s["answer"]]}')

Prompt builders ready.
  Sample Q       : මනු ලොව උපත ලැබීමට ප්‍රථම අප මහා බෝසතාණෝ උපත ලබා සිටියේ,...
  Ground truth   : B -> බ්‍රහ්ම ලොවේය.

## Cell 6 — Load Tripiṭaka Embeddings into Qdrant

Uses **in-memory Qdrant** — no server setup required. Loads `RaniduG/sinhala-tripitaka-embeddings` from HF and indexes all passages.

In [5]:
from datasets import load_dataset as hf_load

print(f'Loading embeddings from {EMBEDDINGS_REPO} ...')
embed_ds = hf_load(EMBEDDINGS_REPO, split='train', token=HF_TOKEN)
print(f'  Rows    : {len(embed_ds)}')
print(f'  Columns : {embed_ds.column_names}')

# Auto-detect vector column and text column
sample = embed_ds[0]
VECTOR_COL, TEXT_COL = None, None
for col in embed_ds.column_names:
    val = sample[col]
    if isinstance(val, (list, np.ndarray)) and len(val) > 50:
        VECTOR_COL = col
    if isinstance(val, str) and len(val) > 5:
        TEXT_COL = col

print(f'  Vector column : {VECTOR_COL}  (dim={len(sample[VECTOR_COL])})')
print(f'  Text column   : {TEXT_COL}')
print(f'  Sample text   : {str(sample[TEXT_COL])[:120]}')

Loading embeddings from RaniduG/sinhala-tripitaka-embeddings ...
  Rows    : 46989
  Columns : ['text', 'title', 'sutta_number', 'nikaya', 'url', 'embedding']
  Vector column : embedding  (dim=1024)
  Text column   : url
  Sample text   : https://tripitaka.online/sutta/5757

In [6]:
from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams, PointStruct
from sentence_transformers import SentenceTransformer

COLLECTION = 'tripitaka'
VECTOR_DIM = len(embed_ds[0][VECTOR_COL])

# In-memory Qdrant — no server, no Docker, everything in-process
qdrant = QdrantClient(':memory:')
qdrant.create_collection(
    collection_name=COLLECTION,
    vectors_config=VectorParams(size=VECTOR_DIM, distance=Distance.COSINE),
)

BATCH = 512
print(f'Indexing {len(embed_ds)} passages (batch={BATCH}) ...')
for start in tqdm(range(0, len(embed_ds), BATCH), desc='Indexing'):
    batch = embed_ds.select(range(start, min(start + BATCH, len(embed_ds))))
    points = [
        PointStruct(
            id=start + i,
            vector=list(map(float, row[VECTOR_COL])),
            payload={'text': row[TEXT_COL]},
        )
        for i, row in enumerate(batch)
    ]
    qdrant.upsert(collection_name=COLLECTION, points=points)

print(f'Qdrant index ready — {len(embed_ds)} passages.')

# Load query encoder (must match what created your embeddings)
print(f'\nLoading query encoder: {QUERY_ENCODER_ID} ...')
query_encoder = SentenceTransformer(QUERY_ENCODER_ID)
enc_dim = query_encoder.get_sentence_embedding_dimension()
print(f'  Encoder dim : {enc_dim}')

if enc_dim != VECTOR_DIM:
    print(f'WARNING: encoder dim ({enc_dim}) != stored vector dim ({VECTOR_DIM})')
    print('Update QUERY_ENCODER_ID in Cell 2 to match the model used to create your embeddings.')
else:
    print('Dimension match confirmed.')


def retrieve_passages(question: str, top_k: int = RAG_TOP_K) -> list:
    """Encode question and return top-k passage texts from Qdrant."""
    # Temporarily move encoder to GPU for encoding, then back to CPU
    query_encoder.to(DEVICE)
    q_vec = query_encoder.encode(question, normalize_embeddings=True).tolist()
    query_encoder.to('cpu')
    
    results = qdrant.query_points(
        collection_name=COLLECTION,
        query=q_vec,
        limit=top_k,
    )
    return [hit.payload['text'] for hit in results.points]

# Quick test
test_q = buddhism_data[0]['question']
test_p = retrieve_passages(test_q)
print(f'\nRetrieval test for: {test_q[:60]}...')
for i, p in enumerate(test_p):
    print(f'  [{i+1}] {str(p)[:100]}')


# Quick test
test_q = buddhism_data[0]['question']
test_p = retrieve_passages(test_q)
print(f'\nRetrieval test for: {test_q[:60]}...')
for i, p in enumerate(test_p):
    print(f'  [{i+1}] {str(p)[:100]}')

Indexing 46989 passages (batch=512) ...

Indexing:   0%|          | 0/92 [00:00<?, ?it/s]

/tmp/ipykernel_3512/2327625794.py:27: UserWarning: Local mode is not recommended for collections with more than 20,000 points. Current collection contains 20480 points. Consider using Qdrant in Docker or Qdrant Cloud for better performance with large datasets.
  qdrant.upsert(collection_name=COLLECTION, points=points)

Qdrant index ready — 46989 passages.

Loading query encoder: intfloat/multilingual-e5-large ...

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

XLMRobertaModel LOAD REPORT from: intfloat/multilingual-e5-large
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

  Encoder dim : 1024
Dimension match confirmed.

Retrieval test for: මනු ලොව උපත ලැබීමට ප්‍රථම අප මහා බෝසතාණෝ උපත ලබා සිටියේ,...
  [1] https://tripitaka.online/sutta/10977
  [2] https://tripitaka.online/sutta/10977
  [3] https://tripitaka.online/sutta/17

Retrieval test for: මනු ලොව උපත ලැබීමට ප්‍රථම අප මහා බෝසතාණෝ උපත ලබා සිටියේ,...
  [1] https://tripitaka.online/sutta/10977
  [2] https://tripitaka.online/sutta/10977
  [3] https://tripitaka.online/sutta/17

## Cell 7 — Model Loader and Memory Helper

In [7]:
def load_model_and_tokenizer(model_id: str, lora_adapter: str = None):
    print(f'\nLoading tokenizer: {model_id}')
    tokenizer = AutoTokenizer.from_pretrained(
        model_id, token=HF_TOKEN, padding_side='left'
    )
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    # Reserve 2 GB headroom for activations and the query encoder
    total_vram_gb = torch.cuda.get_device_properties(0).total_memory / 1e9
    usable_gb     = int(total_vram_gb - 2)
    max_memory    = {0: f'{usable_gb}GiB', 'cpu': '0GiB'}  # forbid CPU offload
    print(f'  VRAM budget : {usable_gb} GB / {total_vram_gb:.0f} GB total')

    if USE_QUANTIZATION:
        print('  Mode: 4-bit NF4')
        bnb = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type='nf4',
            bnb_4bit_compute_dtype=torch.bfloat16,
            bnb_4bit_use_double_quant=True,
        )
        kwargs = dict(
            quantization_config=bnb,
            device_map='auto',
            max_memory=max_memory,
            token=HF_TOKEN,
            attn_implementation='eager',
        )
    else:
        print('  Mode: bfloat16')
        kwargs = dict(
            torch_dtype=torch.bfloat16,
            device_map='auto',
            max_memory=max_memory,
            token=HF_TOKEN,
            attn_implementation='eager',
        )

    model = AutoModelForCausalLM.from_pretrained(model_id, **kwargs)

    if lora_adapter:
        print(f'  Applying LoRA: {lora_adapter}')
        model = PeftModel.from_pretrained(model, lora_adapter, token=HF_TOKEN)

    model.eval()
    print('Model ready.')
    return model, tokenizer


def free_model(model, tokenizer):
    del model, tokenizer
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    print('Model freed from GPU memory.')


print('Model loader ready.')

Model loader ready.

## Cell 8 — Evaluation Engine

In [8]:
def evaluate_model(model, tokenizer, dataset, model_label='Model', use_rag=False):
    """
    Zero-shot MCQ evaluation.
    use_rag=True retrieves Tripitaka passages from Qdrant for each question.
    """
    results = []

    for example in tqdm(dataset, desc=f'[{model_label}]'):
        ground_truth = get_ground_truth_label(example)
        passages     = retrieve_passages(example[QUESTION_KEY]) if use_rag else None
        prompt       = build_prompt(example, tokenizer, context_passages=passages)

        inputs = tokenizer(
            prompt, return_tensors='pt', truncation=True,
            max_length=2048 if use_rag else 1024,
        ).to(DEVICE)

        with torch.no_grad():
            output_ids = model.generate(
                **inputs,
                max_new_tokens=8,
                do_sample=False,
                top_p=None,
                temperature=None,
                pad_token_id=tokenizer.eos_token_id,
            )

        new_tokens     = output_ids[0][inputs['input_ids'].shape[-1]:]
        generated_text = tokenizer.decode(new_tokens, skip_special_tokens=True)
        predicted      = extract_predicted_label(generated_text)
        correct        = predicted == ground_truth

        results.append({
            'question'      : example[QUESTION_KEY][:80] + '...',
            'ground_truth'  : ground_truth,
            'predicted'     : predicted,
            'correct'       : correct,
            'generated_text': generated_text.strip(),
            'rag_used'      : use_rag,
        })

    df      = pd.DataFrame(results)
    acc     = df['correct'].mean() * 100
    invalid = (df['predicted'] == 'X').sum()
    print(f'\n{"="*55}')
    print(f'  [{model_label}]')
    print(f'  Accuracy : {acc:.2f}%  ({int(df["correct"].sum())}/{len(df)})')
    print(f'  Invalid X: {invalid} unparseable predictions')
    print(f'{"="*55}\n')
    return df


print('Evaluation engine ready.')

Evaluation engine ready.

## Cell 9 — Run 1 of 4: Base Model (no RAG)

In [9]:
base_model, base_tokenizer = load_model_and_tokenizer(
    model_id=BASE_MODEL_ID, lora_adapter=None
)

results_base = evaluate_model(
    base_model, base_tokenizer, buddhism_data,
    model_label='Base', use_rag=False
)
results_base.head(5)

Loading tokenizer: meta-llama/Meta-Llama-3.1-8B-Instruct
  VRAM budget : 23 GB / 25 GB total
  Mode: 4-bit NF4

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/184 [00:00<?, ?B/s]

Model ready.

[Base]:   0%|          | 0/132 [00:00<?, ?it/s]

=======================================================
  [Base]
  Accuracy : 2.27%  (3/132)
  Invalid X: 0 unparseable predictions
=======================================================

,question,ground_truth,predicted,correct,generated_text,rag_used
0,මනු ලොව උපත ලැබීමට ප්‍රථම අප මහා බෝසතාණෝ උපත ල...,B,A,False,A,False
1,පංච මහා විලෝකනය හෙවත් පස් මහ බැලුම් වලට අයත් න...,C,A,False,A,False
2,"සිදුහත් බෝසතාණෝ ""මව් කුස පිළිසිඳීම පිළිබඳ සිහි...",D,A,False,A,False
3,"""අග්ගෝ හමස්මි ලෝකස්ස"" මෙහි සරල තේරුම,...",C,A,False,A,False
4,මහාමායා දේවිය කලුරිය කළ පසු සිදුහත් කුමරු හදා ...,D,A,False,A,False

## Cell 10 — Run 2 of 4: Base Model + RAG

In [10]:
# Reuse the same loaded base model — no reload needed
results_base_rag = evaluate_model(
    base_model, base_tokenizer, buddhism_data,
    model_label='Base + RAG', use_rag=True
)
results_base_rag.head(5)

[Base + RAG]:   0%|          | 0/132 [00:00<?, ?it/s]

=======================================================
  [Base + RAG]
  Accuracy : 1.52%  (2/132)
  Invalid X: 0 unparseable predictions
=======================================================

,question,ground_truth,predicted,correct,generated_text,rag_used
0,මනු ලොව උපත ලැබීමට ප්‍රථම අප මහා බෝසතාණෝ උපත ල...,B,A,False,A,True
1,පංච මහා විලෝකනය හෙවත් පස් මහ බැලුම් වලට අයත් න...,C,A,False,A,True
2,"සිදුහත් බෝසතාණෝ ""මව් කුස පිළිසිඳීම පිළිබඳ සිහි...",D,A,False,A,True
3,"""අග්ගෝ හමස්මි ලෝකස්ස"" මෙහි සරල තේරුම,...",C,A,False,A,True
4,මහාමායා දේවිය කලුරිය කළ පසු සිදුහත් කුමරු හදා ...,D,A,False,A,True

## Cell 11 — Free Base Model, Load LoRA Model

In [16]:
# ── Cell 11: Free base model and load LoRA model ─────────────────────────────
import gc, torch

# Re-import everything that the nuclear cleanup may have wiped
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from peft import PeftModel
from sentence_transformers import SentenceTransformer

# Guard delete
for _var in ['base_model', 'base_tokenizer']:
    if _var in globals() and globals()[_var] is not None:
        try:
            globals()[_var].to('cpu')
        except Exception:
            pass
        globals()[_var] = None
del _var

gc.collect()
gc.collect()
torch.cuda.empty_cache()
torch.cuda.synchronize()
torch.cuda.reset_peak_memory_stats()

alloc  = torch.cuda.memory_allocated() / 1e9
reserv = torch.cuda.memory_reserved()  / 1e9
total  = torch.cuda.get_device_properties(0).total_memory / 1e9
print(f"Allocated : {alloc:.2f} GB")
print(f"Reserved  : {reserv:.2f} GB")
print(f"Free est. : {total - reserv:.2f} GB  (total {total:.1f} GB)")

# Re-load query encoder on CPU if wiped
if 'query_encoder' not in globals() or query_encoder is None:
    print("Re-loading query encoder on CPU ...")
    query_encoder = SentenceTransformer(QUERY_ENCODER_ID, device='cpu')
    print(f"  Encoder ready  dim={query_encoder.get_sentence_embedding_dimension()}")
else:
    query_encoder.to('cpu')
    print("Query encoder moved to CPU.")

# Load LoRA model
lora_model, lora_tokenizer = load_model_and_tokenizer(
    model_id=BASE_MODEL_ID, lora_adapter=LORA_ADAPTER_REPO
)
print("Ready for LoRA evaluations.")

Allocated : 5.71 GB
Reserved  : 8.54 GB
Free est. : 16.73 GB  (total 25.3 GB)
Query encoder moved to CPU.

Loading tokenizer: meta-llama/Meta-Llama-3.1-8B-Instruct
  VRAM budget : 23 GB / 25 GB total
  Mode: 4-bit NF4

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

  Applying LoRA: RaniduG/llama-3.1-8b-ift-buddhist-qa-v6

adapter_config.json: 0.00B [00:00, ?B/s]

adapter_model.safetensors:   0%|          | 0.00/168M [00:00<?, ?B/s]

Model ready.
Ready for LoRA evaluations.

## Cell 12 — Run 3 of 4: LoRA Model (no RAG)

In [17]:
results_lora = evaluate_model(
    lora_model, lora_tokenizer, buddhism_data,
    model_label='LoRA', use_rag=False
)
results_lora.head(5)

[LoRA]:   0%|          | 0/132 [00:00<?, ?it/s]

=======================================================
  [LoRA]
  Accuracy : 4.55%  (6/132)
  Invalid X: 0 unparseable predictions
=======================================================

,question,ground_truth,predicted,correct,generated_text,rag_used
0,මනු ලොව උපත ලැබීමට ප්‍රථම අප මහා බෝසතාණෝ උපත ල...,B,A,False,A,False
1,පංච මහා විලෝකනය හෙවත් පස් මහ බැලුම් වලට අයත් න...,C,A,False,A,False
2,"සිදුහත් බෝසතාණෝ ""මව් කුස පිළිසිඳීම පිළිබඳ සිහි...",D,A,False,A,False
3,"""අග්ගෝ හමස්මි ලෝකස්ස"" මෙහි සරල තේරුම,...",C,A,False,A,False
4,මහාමායා දේවිය කලුරිය කළ පසු සිදුහත් කුමරු හදා ...,D,C,False,C,False

## Cell 13 — Run 4 of 4: LoRA Model + RAG

In [18]:
results_lora_rag = evaluate_model(
    lora_model, lora_tokenizer, buddhism_data,
    model_label='LoRA + RAG', use_rag=True
)
results_lora_rag.head(5)

[LoRA + RAG]:   0%|          | 0/132 [00:00<?, ?it/s]

=======================================================
  [LoRA + RAG]
  Accuracy : 9.85%  (13/132)
  Invalid X: 0 unparseable predictions
=======================================================

,question,ground_truth,predicted,correct,generated_text,rag_used
0,මනු ලොව උපත ලැබීමට ප්‍රථම අප මහා බෝසතාණෝ උපත ල...,B,A,False,A,True
1,පංච මහා විලෝකනය හෙවත් පස් මහ බැලුම් වලට අයත් න...,C,A,False,A,True
2,"සිදුහත් බෝසතාණෝ ""මව් කුස පිළිසිඳීම පිළිබඳ සිහි...",D,A,False,A,True
3,"""අග්ගෝ හමස්මි ලෝකස්ස"" මෙහි සරල තේරුම,...",C,A,False,A,True
4,මහාමායා දේවිය කලුරිය කළ පසු සිදුහත් කුමරු හදා ...,D,D,True,D,True

## Cell 14 — Final Comparison Table

In [19]:
def summarise(label, df):
    acc     = df['correct'].mean() * 100
    correct = int(df['correct'].sum())
    invalid = int((df['predicted'] == 'X').sum())
    return {'Model': label, 'Accuracy (%)': round(acc, 2),
            'Correct': correct, 'Total': len(df), 'Invalid (X)': invalid}

summary = pd.DataFrame([
    summarise('1. Base',        results_base),
    summarise('2. Base + RAG',  results_base_rag),
    summarise('3. LoRA',        results_lora),
    summarise('4. LoRA + RAG',  results_lora_rag),
])

base_acc = summary.loc[0, 'Accuracy (%)']
summary['Delta vs Base'] = summary['Accuracy (%)'].apply(
    lambda x: ('+' if x >= base_acc else '') + f'{x - base_acc:.2f}%'
)

print('\n' + '='*65)
print('  FINAL RESULTS — SinhalaMMLU Buddhism Subdomain')
print('='*65)
print(summary.to_string(index=False))
print('='*65)
summary

=================================================================
  FINAL RESULTS — SinhalaMMLU Buddhism Subdomain
=================================================================
        Model  Accuracy (%)  Correct  Total  Invalid (X) Delta vs Base
      1. Base          2.27        3    132            0        +0.00%
2. Base + RAG          1.52        2    132            0        -0.75%
      3. LoRA          4.55        6    132            0        +2.28%
4. LoRA + RAG          9.85       13    132            0        +7.58%
=================================================================

           Model  Accuracy (%)  Correct  Total  Invalid (X) Delta vs Base
0        1. Base          2.27        3    132            0        +0.00%
1  2. Base + RAG          1.52        2    132            0        -0.75%
2        3. LoRA          4.55        6    132            0        +2.28%
3  4. LoRA + RAG          9.85       13    132            0        +7.58%

## Cell 15 — Export All Results

In [20]:
results_base.to_csv('results_1_base.csv',             index=False)
results_base_rag.to_csv('results_2_base_rag.csv',     index=False)
results_lora.to_csv('results_3_lora.csv',             index=False)
results_lora_rag.to_csv('results_4_lora_rag.csv',     index=False)
summary.to_csv('results_summary_all_models.csv',      index=False)

print('Saved: results_1_base.csv')
print('Saved: results_2_base_rag.csv')
print('Saved: results_3_lora.csv')
print('Saved: results_4_lora_rag.csv')
print('Saved: results_summary_all_models.csv')

Saved: results_1_base.csv
Saved: results_2_base_rag.csv
Saved: results_3_lora.csv
Saved: results_4_lora_rag.csv
Saved: results_summary_all_models.csv

## Cell 16 — Error Analysis: Where does RAG help and where does LoRA help?

In [21]:
def rag_impact(no_rag_df, rag_df, label):
    comp = pd.DataFrame({
        'question'    : no_rag_df['question'].values,
        'ground_truth': no_rag_df['ground_truth'].values,
        'no_rag_pred' : no_rag_df['predicted'].values,
        'rag_pred'    : rag_df['predicted'].values,
        'no_rag_ok'   : no_rag_df['correct'].values,
        'rag_ok'      : rag_df['correct'].values,
    })
    fixed  = comp[(~comp['no_rag_ok']) &  comp['rag_ok']]
    broken = comp[ comp['no_rag_ok']  & ~comp['rag_ok']]
    print(f'\n-- {label} --')
    print(f'  RAG fixed  (wrong -> right) : {len(fixed)}')
    print(f'  RAG broke  (right -> wrong) : {len(broken)}')
    print(f'  Net gain                    : {len(fixed) - len(broken)}')
    return fixed, broken

rag_impact(results_base, results_base_rag, 'Base model: RAG impact')
rag_impact(results_lora, results_lora_rag, 'LoRA model: RAG impact')

# LoRA vs Base comparison (no RAG)
comp2 = pd.DataFrame({
    'question'    : results_base['question'].values,
    'ground_truth': results_base['ground_truth'].values,
    'base_pred'   : results_base['predicted'].values,
    'lora_pred'   : results_lora['predicted'].values,
    'base_ok'     : results_base['correct'].values,
    'lora_ok'     : results_lora['correct'].values,
})
lora_wins = comp2[(~comp2['base_ok']) &  comp2['lora_ok']]
base_wins = comp2[ comp2['base_ok']  & ~comp2['lora_ok']]
print(f'\n-- LoRA vs Base (no RAG) --')
print(f'  LoRA better than Base : {len(lora_wins)}')
print(f'  Base better than LoRA : {len(base_wins)}')
print(f'  Net LoRA gain         : {len(lora_wins) - len(base_wins)}')

print('\nSample questions where LoRA helped:')
display(lora_wins[['question','ground_truth','base_pred','lora_pred']].head(5))

-- Base model: RAG impact --
  RAG fixed  (wrong -> right) : 0
  RAG broke  (right -> wrong) : 1
  Net gain                    : -1

-- LoRA model: RAG impact --
  RAG fixed  (wrong -> right) : 8
  RAG broke  (right -> wrong) : 1
  Net gain                    : 7

-- LoRA vs Base (no RAG) --
  LoRA better than Base : 6
  Base better than LoRA : 3
  Net LoRA gain         : 3

Sample questions where LoRA helped:

,question,ground_truth,base_pred,lora_pred
24,"නිබ්බුත පද පවසන ලද්දේ,...",C,A,C
27,පුද්ගලයෙකුගේ මනස සංවර කර ගැනීමට මෙත් වැඩීම මහත...,D,A,D
30,සතර පෙරනිමිතිවල දෙවැන්න...,C,A,C
79,බුදුරජාණන් වහන්සේ භික්ෂූන් වහන්සේලාට ඕවාද ප්‍ර...,C,A,C
115,බුදුරජාණන් වහන්සේ සියලු සංස්කාර ධර්මයන්ගේ අනිත...,B,A,B